Added phantomjs rasterize function

diff --git a/.bash/commands b/.bash/commands
--- a/.bash/commands
+++ b/.bash/commands
@@ -145,3 +145,26 @@ function gf() {
 AWK
   )" | less -R
 }
+
+function rasterize() {
+  local address="$1"
+  local output="$2"
+  if [[ $address && $output ]]; then
+    phantomjs <(echo "
+      var page = new WebPage();
+      page.viewportSize = { width: 600, height: 600 };
+      page.open(${address}, function (status) {
+        if (status !== 'success') console.log('Unable to load the address!');
+        else {
+          window.setTimeout(function() {
+            page.render(${output});
+            phantom.exit();
+          }, 200);
+        }
+      };
+    ")
+  else
+    echo "Usage: rasterize URL filename"
+    exit 1
+  fi
+}
